/**
 * Shared DOM element lookups used by the app.
 */
export const elements = {
  monthSelect: document.querySelector("#month-select"),
  yearSelect: document.querySelector("#year-select"),
  workerForm: document.querySelector("#worker-form"),
  workerSubmitButton: document.querySelector("#worker-submit-btn"),
  cancelEditButton: document.querySelector("#cancel-edit-btn"),
  workerListElement: document.querySelector("#worker-list"),
  generateButton: document.querySelector("#generate-btn"),
  exportButton: document.querySelector("#export-btn"),
  exportJsonButton: document.querySelector("#export-json-btn"),
  importJsonInput: document.querySelector("#import-json-input"),
  helpButton: document.querySelector("#help-btn"),
  scheduleOutput: document.querySelector("#schedule-output"),
  schedulePeriod: document.querySelector("#schedule-period"),
  warningsList: document.querySelector("#warnings-list"),
  warningsSection: document.querySelector("#warnings-section"),
  notesSection: document.querySelector("#notes-section"),
  notesInput: document.querySelector("#notes-input"),
  summaryCardsContainer: document.querySelector("#summary-cards"),
  workerRowTemplate: document.querySelector("#worker-row-template"),
  workerModal: document.querySelector("#worker-modal"),
  workerModalTitle: document.querySelector("#modal-title"),
  openWorkerModalButton: document.querySelector("#open-worker-modal"),
  closeWorkerModalButton: document.querySelector("#close-worker-modal"),
  openSettingsModalButton: document.querySelector("#open-settings-modal"),
  closeSettingsModalButton: document.querySelector("#close-settings-modal"),
  settingsModal: document.querySelector("#settings-modal"),
  settingsForm: document.querySelector("#settings-form"),
  settingsMaxStreakDayInput: document.querySelector("#settings-max-streak-day"),
  settingsMaxStreakNightInput: document.querySelector("#settings-max-streak-night"),
  settingsMaxStreakAnyInput: document.querySelector("#settings-max-streak-any"),
  cancelSettingsButton: document.querySelector("#cancel-settings-btn"),
  workerBlockShifts: document.querySelector("#worker-block-shifts"),
  blockAllButton: document.querySelector("#block-all-btn"),
  unblockAllButton: document.querySelector("#unblock-all-btn"),
  workerColorInput: document.querySelector("#worker-color"),
  settingsUseWorkerColors: document.querySelector("#settings-use-worker-colors"),
};
